apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-backend
  labels:
    app: sa-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-backend
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-backend
    spec:
      containers:
        - name: sa-backend
          image: rishijatania/sentiment-analysis-backend:minikube
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
