apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-webapp
  labels:
    app: sa-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sa-webapp
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: sa-webapp
    spec:
      containers:
        - name: sa-webapp
          image: rishijatania/sentiment-analysis-web-app:minikube
          imagePullPolicy: Always
          env:
            - name: SA_LOGIC_API_URL
              value: "http://sa-backend:5000"
          ports:
            - containerPort: 8080
